llm:
  default_provider: "mega_llm"
  default_model: "openai-gpt-oss-120b"

agents:
  role_identification:
    llm_provider: "mega_llm"
    llm_model: "openai-gpt-oss-120b"
  text_normalization:
    llm_provider: "mega_llm"
    llm_model: "openai-gpt-oss-120b"
  form_filling:
    llm_provider: "mega_llm"
    llm_model: "openai-gpt-oss-120b"
  document_export:
    llm_provider: "mega_llm"
    llm_model: "openai-gpt-oss-120b"

workflows:
  default: "default_workflow"
  default_workflow:
    agents: ["researcher"]
    checkpointer: false
  form_docx_workflow:
    agents: ["text_normalization", "form_filling", "document_export"]
    checkpointer: false
  conversation_workflow:
    agents: ["role_identification", "text_normalization", "form_filling", "document_export"]
    checkpointer: false

voice_agent:
  agent_name: "data-collection-agent"
  stt: "deepgram/nova-3:multi"
  llm_model: "gpt-4.1-mini"
  tts: "cartesia/sonic-3:9626c31c-bec5-4cca-baa8-f8ba9e84c8bc"
  default_fields:
    - "Họ và tên (full_name)"
    - "Số điện thoại (phone_number)"
    - "Số bảo hiểm y tế (health_insurance_number)"
    - "Tiền sử bệnh lý (medical_history)"
    - "Triệu chứng hiện tại (symptoms)"

models:
  asr_path: "C:\\Users\\kans\\.cache\\huggingface\\hub\\models--nvidia--parakeet-ctc-0.6b-vi\\snapshots\\b0493142b49458810324e3db8be9e8e07b4ebc17\\parakeet-ctc-0.6b-vi.nemo"
  diarization_path: "D:\\nvidia parakeet\\diar_streaming_sortformer_4spk-v2.nemo"

database:
  type: "memory"
